test:gcc:
  image: fedora
  #artifacts:
  #  expire_in: 3 hour
  #  paths:
  #    - ${CI_PROJECT_DIR}
  script:
    - echo "proxy=http://proxyout.lanl.gov:8080" >> /etc/dnf/dnf.conf
    - dnf install -y make gcc gcc-gfortran gcc-c++ perl findutils which git
    - git clone https://${EOSPAC6_CI_USERNAME}:${EOSPAC6_CI_PASSWORD}@git.lanl.gov/eos/eospac-dev/eospac6-data.git
    - export SESAMEPATH="${CI_PROJECT_DIR}/eospac6-data/data/eos:${CI_PROJECT_DIR}/eospac6-data/data/eos/export-controlled/ieee64"
    - cd Source/
    - export CORECOUNT=$(./scripts/corecount)
    - echo "CORECOUNT=${CORECOUNT}"
    - make -j ${CORECOUNT} check 2>&1 | tee tmp.out
    - |
      if [ "$(grep -c "FAILED" tmp.out)" -ge 1 ]; 
      then exit 1; 
      fi
    - rm tmp.out
    - make install prefix=${CI_PROJECT_DIR}/install
