/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MySesIO_SesIO */

#ifndef _Included_MySesIO_SesIO
#define _Included_MySesIO_SesIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MySesIO_SesIO
 * Method:    SesAccessDirectory
 * Signature: (I[J[J[JJJ)J
 */
JNIEXPORT jlong JNICALL Java_MySesIO_SesIO_SesAccessDirectory
  (JNIEnv *, jobject, jint, jlongArray, jlongArray, jlongArray, jlong, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesAccessTableIndex
 * Signature: (I[J[J[JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_MySesIO_SesIO_SesAccessTableIndex
  (JNIEnv *, jobject, jint, jlongArray, jlongArray, jlongArray, jlong, jlong, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesArraySizeNext
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_MySesIO_SesIO_SesArraySizeNext
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesChangeNext
 * Signature: (I[DJ)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesChangeNext
  (JNIEnv *, jobject, jint, jdoubleArray, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesCombine
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesCombine
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesComments
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MySesIO_SesIO_SesComments
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesDate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MySesIO_SesIO_SesDate
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesDefineTable
 * Signature: (ILjava/lang/String;JJJJ[J[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesDefineTable
  (JNIEnv *, jobject, jint, jstring, jlong, jlong, jlong, jlong, jlongArray, jobjectArray);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesDeleteNext
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesDeleteNext
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesDeleteTable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesDeleteTable
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesGetLabel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MySesIO_SesIO_SesGetLabel
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesGetMaterialID
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesGetMaterialID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesGetMaterials
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_MySesIO_SesIO_SesGetMaterials
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesGetTableIDS
 * Signature: (IJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_MySesIO_SesIO_SesGetTableIDS
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesHasNext
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_MySesIO_SesIO_SesHasNext
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesIndicatesError
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_MySesIO_SesIO_SesIndicatesError
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesIsValid
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_MySesIO_SesIO_SesIsValid
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesOpen
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesOpen
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesPrintErrorCondition
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MySesIO_SesIO_SesPrintErrorCondition
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesRead1D
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MySesIO_SesIO_SesRead1D
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesRead2D
 * Signature: (III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MySesIO_SesIO_SesRead2D
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesRead3D
 * Signature: (IIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MySesIO_SesIO_SesRead3D
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesReadNamedArray
 * Signature: (ILjava/lang/String;I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MySesIO_SesIO_SesReadNamedArray
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesReadNext
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MySesIO_SesIO_SesReadNext
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesReadNumber
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_MySesIO_SesIO_SesReadNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesReadPairs
 * Signature: (I[D[DJ)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesReadPairs
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesReadWord
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_MySesIO_SesIO_SesReadWord
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetArrayOrder
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetArrayOrder
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetDate
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetDate
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetGrid
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetGrid
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetFormat
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetFormat
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetLabel
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetLabel
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetMaterialOrder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetMaterialOrder
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetSignificantDigits
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetSignificantDigits
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetup
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetup
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SetSetTableIndex
 * Signature: (IJJJ)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SetSetTableIndex
  (JNIEnv *, jobject, jint, jlong, jlong, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetValidate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetValidate
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSetVersion
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSetVersion
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesSkip
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesSkip
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesVersion
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MySesIO_SesIO_SesVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesWrite1D
 * Signature: (I[DI)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesWrite1D
  (JNIEnv *, jobject, jint, jdoubleArray, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesWrite2D
 * Signature: (I[DII)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesWrite2D
  (JNIEnv *, jobject, jint, jdoubleArray, jint, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesWrite3D
 * Signature: (I[DIII)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesWrite3D
  (JNIEnv *, jobject, jint, jdoubleArray, jint, jint, jint);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesWriteComments
 * Signature: (ILjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesWriteComments
  (JNIEnv *, jobject, jint, jstring, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesWriteNext
 * Signature: (I[DILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesWriteNext
  (JNIEnv *, jobject, jint, jdoubleArray, jint, jstring);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesWriteNumber
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesWriteNumber
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesWritePairs
 * Signature: (I[D[DJ)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesWritePairs
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jlong);

/*
 * Class:     MySesIO_SesIO
 * Method:    SesWriteWord
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_MySesIO_SesIO_SesWriteWord
  (JNIEnv *, jobject, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
