/*********************************************************************
 * Header file auto-generated by Makefile
 *********************************************************************/
static char *help_str =
  "SOURCE FILE: get_machprec.c\n"
  "\n"
  "DETAILED DESCRIPTION\n"
  "     This is a simple utility to display the platform-specific precision\n"
  "              information used within EOSPAC6.\n"
  "     \n"
  "PRECONDITION\n"
  "     libeospac6.a (version 6.2 or later) is required\n"
  "     \n"
  "AUTHOR\n"
  "     David A. Pimentel\n"
  "     \n"
  "STDOUT\n"
  "            Platform-specific precision information returned.\n"
  "     \n"
  "STDERR\n"
  "            All error messages are returned.\n"
  "     \n"
  "USAGE\n"
  "            get_machprec\n"
  "     \n"
  "     -h\n"
  "                   Display the basic usage of this tool.\n"
  "     \n"
  ;
