/*********************************************************************
 * Header file auto-generated by Makefile
 *********************************************************************/
static char *help_str =
  "SOURCE FILE: getopt_driver.c\n"
  "\n"
  "DETAILED DESCRIPTION\n"
  "     Simple MAIN to demonstrate getoptions usage\n"
  "     \n"
  "AUTHOR\n"
  "     David A. Pimentel\n"
  "     \n"
  "DATE\n"
  "     2010-02-19 13:52:45 MST\n"
  "     \n"
  "STDERR\n"
  "            All information and error messages are returned\n"
  "     \n"
  "USAGE\n"
  "              <cmd> '<option_string>' [<options>] [<arguments>]\n"
  "     \n"
  ;
