/*********************************************************************
 * Header file auto-generated by Makefile
 *********************************************************************/
static char *help_str =
  "SOURCE FILE: sampler.c\n"
  "\n"
  "DETAILED DESCRIPTION\n"
  "     Simple MAIN to demonstrate sampler usage\n"
  "     \n"
  "AUTHOR\n"
  "     David A. Pimentel\n"
  "     \n"
  "DATE\n"
  "     2013-09-09 18:16:16 MDT\n"
  "     \n"
  "STDERR\n"
  "            All information and error messages are returned\n"
  "     \n"
  "USAGE\n"
  "              <cmd> '<option_string>' [<options>] [<arguments>]\n"
  "     \n"
  ;
