/*********************************************************************
 *
 * Filetype: (HEADER)
 *
 * Automatically generated by cflow.filter.pl, Mon Aug 25 16:13:43 2014
 *
 * Copyright -- see file named COPYRIGHTNOTICE
 * 
 *********************************************************************/
#ifndef EOS_SESUTILS_PROTOTYPES

#define EOS_SESUTILS_PROTOTYPES

/*
 * ------------------------------------------------
 * 6 PUBLIC FUNCTION PROTOTYPES FOR eos_SesUtils.c
 * ------------------------------------------------
 */
EOS_INTEGER _eos_SesQuickSort (EOS_INTEGER N, ses_material_id a[], EOS_INTEGER lvl, EOS_INTEGER * err,
			       EOS_CHAR ** errMsg);
EOS_INTEGER eos_SesCleanFileCache (void);
EOS_INTEGER eos_SesGetBulkData (EOS_INTEGER materialID, EOS_BOOLEAN userDefinedDataFile, EOS_INTEGER dataFileIndex,
				EOS_REAL * zbar, EOS_REAL * abar, EOS_REAL * dens0, EOS_REAL * solidBulkModulus,
				EOS_REAL * exchangeCoeff, EOS_CHAR ** errMsg);
EOS_INTEGER eos_SesGetFileInfoFromCache (EOS_INTEGER jfile, EOS_INTEGER * nmats,
					 ses_material_id_reference * indexdata, ses_file_handle * sesFile);
EOS_INTEGER eos_SesLoadSesameFiles (ses_material_id mid, ses_table_id tid, EOS_INTEGER fileIndex, EOS_REAL ** ptr,
				    EOS_INTEGER nreals);
EOS_INTEGER eos_SesSeekToDataTable (EOS_INTEGER matid, EOS_INTEGER tableNum, EOS_REAL ** ptr, EOS_INTEGER nreals,
				    EOS_INTEGER * fileIndex, ses_material_id_reference omid,
				    ses_table_id_reference otid, EOS_INTEGER * dataSize,
				    EOS_BOOLEAN userDefinedDataFile, EOS_CHAR ** errMsg);

#ifdef _EOS_SESUTILS_INTERNAL_PROTOTYPES

/*
 * -------------------------------------------------
 * 3 PRIVATE FUNCTION PROTOTYPES FOR eos_SesUtils.c
 * -------------------------------------------------
 */
EOS_INTEGER _eos_SesSeekToDataTable (EOS_CHAR ** sesameFiles, EOS_INTEGER sesameFilesL, EOS_INTEGER matid,
				     EOS_INTEGER tableNum, EOS_BOOLEAN userDefinedDataFile, EOS_REAL ** ptr,
				     EOS_INTEGER nreals, ses_material_id_reference omid,
				     ses_table_id_reference otid, EOS_INTEGER * fileIndex, EOS_INTEGER * dataSize,
				     EOS_CHAR ** errMsg);
long ses_get_table_size (ses_file_handle sesFile, ses_material_id mid, ses_table_id tid);
ses_error_flag ses_table_dates (ses_file_handle sesFile, long *date1, long *date2, long *vers);

#endif /* _EOS_SESUTILS_INTERNAL_PROTOTYPES */

#endif /* EOS_SESUTILS_PROTOTYPES */
