/*********************************************************************
 *
 * Filetype: (HEADER)
 *
 * Automatically generated by cflow.filter.pl, Mon Aug 25 16:13:34 2014
 *
 * Copyright -- see file named COPYRIGHTNOTICE
 * 
 *********************************************************************/
#ifndef EOS_DATA_PROTOTYPES

#define EOS_DATA_PROTOTYPES

/*
 * ---------------------------------------------
 * 13 PUBLIC FUNCTION PROTOTYPES FOR eos_Data.c
 * ---------------------------------------------
 */
EOS_BOOLEAN _eos_AreOptionsCompatibleEosData (eos_Data * obj1, eos_Data * obj2, EOS_INTEGER dataType,
					      EOS_INTEGER monDataType, EOS_INTEGER * optFlags, EOS_BOOLEAN * bval,
					      EOS_INTEGER nopt);
EOS_BOOLEAN _eos_AreOptionsDefaultEosData (eos_Data * obj1);
EOS_BOOLEAN _isOptionDefaultEosData (eos_Data *obj1, EOS_INTEGER of, EOS_INTEGER dataType);
void _eos_CopyOptionsEosData (eos_Data * obj1, eos_Data * obj2);
eos_OptionValue *_eos_getOptionEosData (eos_Data * me, EOS_INTEGER optFlag);
eos_Data *eos_AllocEosData (EOS_INTEGER materialID, EOS_INTEGER th);
void eos_ConstructEosData (eos_Data * me, EOS_INTEGER th, EOS_INTEGER materialID);
void eos_DestroyEosData (eos_Data * ptr);
void eos_FreeEosData (eos_Data ** ptr, EOS_INTEGER recordType);
EOS_BOOLEAN _eos_IsaShareableObjectEosData (void *ptr);
void eos_GetPackedOptionsSizeEosData (eos_Data * me, EOS_INTEGER * byteCount, EOS_INTEGER * errorCode);
void eos_PackOptionsEosData (eos_Data * me, EOS_CHAR * packedData, EOS_INTEGER * byteCount,
			     EOS_INTEGER * errorCode);
void eos_ResetOptionEosData (eos_Data * me, EOS_INTEGER dataType, EOS_INTEGER monDataType, EOS_INTEGER tableOption,
			     EOS_INTEGER * errorCode);
void eos_SetOptionEosData (eos_Data * me, EOS_INTEGER dataType, EOS_INTEGER monDataType, EOS_INTEGER tableOption,
			   EOS_REAL tableOptionVal, EOS_INTEGER * errorCode);
void eos_UnpackOptionsEosData (eos_Data * me, EOS_CHAR * packedData, EOS_INTEGER * errorCode);

#ifdef _EOS_DATA_INTERNAL_PROTOTYPES

/*
 * ---------------------------------------------
 * 1 PRIVATE FUNCTION PROTOTYPES FOR eos_Data.c
 * ---------------------------------------------
 */
void eos_HandleErrorEosData (void *ptr, EOS_INTEGER th, EOS_INTEGER errorCode);

#endif /* _EOS_DATA_INTERNAL_PROTOTYPES */

#endif /* EOS_DATA_PROTOTYPES */
