/*********************************************************************
 *
 * Filetype: (HEADER)
 *
 * Automatically generated by cflow.filter.pl, Mon Aug 25 16:13:35 2014
 *
 * Copyright -- see file named COPYRIGHTNOTICE
 * 
 *********************************************************************/
#ifndef EOS_ERRORHANDLER_PROTOTYPES

#define EOS_ERRORHANDLER_PROTOTYPES

/*
 * ----------------------------------------------------
 * 3 PUBLIC FUNCTION PROTOTYPES FOR eos_ErrorHandler.c
 * ----------------------------------------------------
 */
void eos_ConstructEosErrorHandler (eos_ErrorHandler * me);
void eos_DestroyEosErrorHandler (eos_ErrorHandler * me);
EOS_CHAR *eos_GetErrorMsg (EOS_INTEGER errorCode);

#ifdef _EOS_ERRORHANDLER_INTERNAL_PROTOTYPES

/*
 * -----------------------------------------------------
 * 0 PRIVATE FUNCTION PROTOTYPES FOR eos_ErrorHandler.c
 * -----------------------------------------------------
 */

#endif /* _EOS_ERRORHANDLER_INTERNAL_PROTOTYPES */

#endif /* EOS_ERRORHANDLER_PROTOTYPES */
