/*********************************************************************
 *
 * Filetype: (HEADER)
 *
 * Automatically generated by cflow.filter.pl, Mon Oct 22 15:55:30 2018
 *
 * Copyright -- see file named COPYRIGHTNOTICE
 * 
 *********************************************************************/
#ifndef EOS_RECORDTYPE1INTERP_PROTOTYPES

#define EOS_RECORDTYPE1INTERP_PROTOTYPES

/*
 * ---------------------------------------------------------
 * 6 PUBLIC FUNCTION PROTOTYPES FOR eos_RecordType1Interp.c
 * ---------------------------------------------------------
 */
EOS_INTEGER _eos_EvaluateTaylorFor_dataType_DT (eos_Taylor *T, EOS_REAL x, EOS_REAL y, EOS_REAL *f, EOS_REAL *dFx, EOS_REAL *dFy);
EOS_INTEGER _eos_EvaluateTransformedTaylorFor_Pt_DT (eos_Taylor *T, EOS_REAL x, EOS_REAL y, EOS_REAL *f, EOS_REAL *dFx, EOS_REAL *dFy);
EOS_INTEGER _eos_EvaluateTransformedTaylorFor_St_DT (eos_Taylor *T, EOS_REAL x, EOS_REAL y, EOS_REAL *f, EOS_REAL *dFx, EOS_REAL *dFy);
EOS_INTEGER _eos_EvaluateTransformedTaylorFor_Ut_DT (eos_Taylor *T, EOS_REAL x, EOS_REAL y, EOS_REAL *f, EOS_REAL *dFx, EOS_REAL *dFy);
void eos_CheckExtrapRecordType1_using_extrapolationBounds (void *ptr, EOS_INTEGER th, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);
void eos_InterpolateRecordType1 (void *ptr, EOS_INTEGER th, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_REAL *fVals, EOS_REAL *dFx, EOS_REAL *dFy, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);

#ifdef _EOS_RECORDTYPE1INTERP_INTERNAL_PROTOTYPES

/*
 * ----------------------------------------------------------
 * 2 PRIVATE FUNCTION PROTOTYPES FOR eos_RecordType1Interp.c
 * ----------------------------------------------------------
 */
void _eos_EvaluateTaylorRecordType1 (void *ptr, EOS_INTEGER th, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_REAL *fVals, EOS_REAL *dFx, EOS_REAL *dFy, EOS_REAL *dFCx, EOS_REAL *dFx0, EOS_REAL *dFy0, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);
void _eos_InterpolateRecordType1 (void *ptr, EOS_INTEGER th, EOS_INTEGER varOrder, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_REAL *fVals, EOS_REAL *dFx, EOS_REAL *dFy, EOS_REAL *dFCx, EOS_REAL *dFx0, EOS_REAL *dFy0, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);
void _eos_InterpolateRecordType1GpuLimited (void *ptr, EOS_INTEGER th, EOS_INTEGER varOrder, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_REAL *fVals, EOS_REAL *dFx, EOS_REAL *dFy, EOS_REAL *dFCx, EOS_REAL *dFx0, EOS_REAL *dFy0, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);

#endif /* _EOS_RECORDTYPE1INTERP_INTERNAL_PROTOTYPES */

#endif /* EOS_RECORDTYPE1INTERP_PROTOTYPES */
