/*********************************************************************
 *
 * Filetype: (HEADER)
 *
 * Automatically generated by cflow.filter.pl, Mon Aug 25 16:13:33 2014
 *
 * Copyright -- see file named COPYRIGHTNOTICE
 * 
 *********************************************************************/
#ifndef EOS_ACCESS_PROTOTYPES

#define EOS_ACCESS_PROTOTYPES

/*
 * ----------------------------------------------
 * 2 PUBLIC FUNCTION PROTOTYPES FOR eos_Access.c
 * ----------------------------------------------
 */
void eos_ConstructEosAccess (eos_Access * me);
void eos_DestroyEosAccess (eos_Access * me);

#ifdef _EOS_ACCESS_INTERNAL_PROTOTYPES

/*
 * -----------------------------------------------
 * 1 PRIVATE FUNCTION PROTOTYPES FOR eos_Access.c
 * -----------------------------------------------
 */
void eos_HandleErrorEosAccess (void *ptr, EOS_INTEGER th, EOS_INTEGER errorCode);

#endif /* _EOS_ACCESS_INTERNAL_PROTOTYPES */

#endif /* EOS_ACCESS_PROTOTYPES */
