/*********************************************************************
 *
 * Filetype: (HEADER)
 *
 * Automatically generated by cflow.filter.pl, Mon Oct 22 17:53:52 2018
 *
 * Copyright -- see file named COPYRIGHTNOTICE
 * 
 *********************************************************************/
#ifndef EOS_RECORDTYPE6INTERP_PROTOTYPES

#define EOS_RECORDTYPE6INTERP_PROTOTYPES

/*
 * ---------------------------------------------------------
 * 3 PUBLIC FUNCTION PROTOTYPES FOR eos_RecordType6Interp.c
 * ---------------------------------------------------------
 */
void _eos_InterpolateRecordType6 (void *ptr, EOS_INTEGER th, EOS_INTEGER subTableNum, EOS_INTEGER varOrder, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_REAL *fVals, EOS_REAL *dFx, EOS_REAL *dFy, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);
void eos_CheckExtrapRecordType6 (void *ptr, EOS_INTEGER th, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);
void eos_InterpolateRecordType6 (void *ptr, EOS_INTEGER th, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_REAL *fVals, EOS_REAL *dFx, EOS_REAL *dFy, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);

#ifdef _EOS_RECORDTYPE6INTERP_INTERNAL_PROTOTYPES

/*
 * ----------------------------------------------------------
 * 0 PRIVATE FUNCTION PROTOTYPES FOR eos_RecordType6Interp.c
 * ----------------------------------------------------------
 */

#endif /* _EOS_RECORDTYPE6INTERP_INTERNAL_PROTOTYPES */

#endif /* EOS_RECORDTYPE6INTERP_PROTOTYPES */
