/*********************************************************************
 *
 * Filetype: (HEADER)
 *
 * Automatically generated by cflow.filter.pl, Mon Oct 22 16:32:09 2018
 *
 * Copyright -- see file named COPYRIGHTNOTICE
 * 
 *********************************************************************/
#ifndef EOS_RECORDTYPE2INTERP_PROTOTYPES

#define EOS_RECORDTYPE2INTERP_PROTOTYPES

/*
 * ---------------------------------------------------------
 * 2 PUBLIC FUNCTION PROTOTYPES FOR eos_RecordType2Interp.c
 * ---------------------------------------------------------
 */
void eos_CheckExtrapRecordType2 (void *ptr, EOS_INTEGER th, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);
void eos_InterpolateRecordType2 (void *ptr, EOS_INTEGER th, EOS_INTEGER dataType, EOS_INTEGER nXYPairs, EOS_REAL *srchX, EOS_REAL *srchY, EOS_REAL *fVals, EOS_REAL *dFx, EOS_REAL *dFy, EOS_INTEGER *xyBounds, EOS_INTEGER *errorCode);

#ifdef _EOS_RECORDTYPE2INTERP_INTERNAL_PROTOTYPES

/*
 * ----------------------------------------------------------
 * 0 PRIVATE FUNCTION PROTOTYPES FOR eos_RecordType2Interp.c
 * ----------------------------------------------------------
 */

#endif /* _EOS_RECORDTYPE2INTERP_INTERNAL_PROTOTYPES */

#endif /* EOS_RECORDTYPE2INTERP_PROTOTYPES */
