/*.......................................................
 *  ./eos_version.c
 *    Creation date: 12-05-2016 08:16:09 AM MST
 *    This file is automatically generated by /tmp/eospac6.50309/eospac6/Source/scripts/eos_version.pl
 *.......................................................*/
#include "eos_types.h"
#include "eos_wrappers.h"
#include <string.h>

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef _EOS_INCLUDE_SPECIAL_FUNCTION
void eos_version_name_EOSPAC_v6_3_1_r20161202150449()
{
  return;
}
#endif

static EOS_CHAR *eos_version_info_msg = "EOSPAC v6.3.1 r20161202150449";
void FUNC_INTER eos_GetVersionLength(EOS_INTEGER *length)
{
  /* include space for the '\0' character */
  *length = strlen(eos_version_info_msg) + 1;
}

void FUNC_INTER eos_GetVersion(EOS_CHAR *version)
{
  strcpy(version, eos_version_info_msg);
  return;
}

#ifdef __cplusplus
}
#endif

