/*********************************************************************
 *
 * Filetype: (HEADER)
 *
 * Automatically generated by cflow.filter.pl, Mon Aug 25 16:13:42 2014
 *
 * Copyright -- see file named COPYRIGHTNOTICE
 * 
 *********************************************************************/
#ifndef EOS_RECORDTYPE5_PROTOTYPES

#define EOS_RECORDTYPE5_PROTOTYPES

/*
 * ---------------------------------------------------
 * 1 PUBLIC FUNCTION PROTOTYPES FOR eos_RecordType5.c
 * ---------------------------------------------------
 */
void eos_ConstructRecordType5 (eos_RecordType5 * me, EOS_INTEGER th, EOS_INTEGER materialID);

#ifdef _EOS_RECORDTYPE5_INTERNAL_PROTOTYPES

/*
 * -----------------------------------------------------
 * 19 PRIVATE FUNCTION PROTOTYPES FOR eos_RecordType5.c
 * -----------------------------------------------------
 */
void eos_AreMonotonicRequirementsCompatibleRecordType5 (void *me, EOS_INTEGER dataType, EOS_INTEGER inX,
							EOS_INTEGER inY, EOS_BOOLEAN * compatible);
void eos_AreSmoothingRequirementsCompatibleRecordType5 (void *me, EOS_INTEGER dataType, EOS_INTEGER makeSmooth,
							EOS_INTEGER makePtSmooth, EOS_BOOLEAN * compatible);
void eos_CreateRecordType5 (void *ptr, EOS_INTEGER th);
void eos_DestroyRecordType5 (void *ptr);
void eos_GetLoadedBulkDataRecordType5 (void *ptr, EOS_REAL * zbar, EOS_REAL * abar, EOS_REAL * dens0,
				       EOS_INTEGER * errorCode);
void eos_GetMonotonicityRecordType5 (void *me, EOS_INTEGER dataType, EOS_INTEGER * inX, EOS_INTEGER * inY);
void eos_GetPackedTableRecordType5 (void *ptr, EOS_INTEGER th, EOS_CHAR * packedTable, EOS_INTEGER * err);
void eos_GetPackedTableSizeRecordType5 (void *ptr, EOS_INTEGER th, EOS_INTEGER * packedTableSize,
					EOS_INTEGER * err);
void eos_GetSmoothingRecordType5 (void *me, EOS_INTEGER dataType, EOS_INTEGER * isSmooth,
				  EOS_INTEGER * isPtSmooth);
void eos_GetTableMetaDataRecordType5 (void *ptr, EOS_INTEGER infoItem, EOS_CHAR *infoStr, EOS_INTEGER *err);
void eos_GetTableInfoRecordType5 (void *ptr, EOS_INTEGER th, EOS_INTEGER numInfoItems, EOS_INTEGER * infoItems,
				  EOS_REAL * infoVals, EOS_INTEGER * err);
void eos_IsMonotonicRecordType5 (void *ptr, EOS_INTEGER dataType, EOS_BOOLEAN * isMonotonic, EOS_BOOLEAN inX,
				 EOS_BOOLEAN inY, EOS_INTEGER * err);
void eos_LoadRecordType5 (void *ptr, EOS_INTEGER th);
void eos_MakeMonotonicRecordType5 (void *ptr, EOS_INTEGER th, EOS_INTEGER dataType, EOS_BOOLEAN inX,
				   EOS_BOOLEAN inY, EOS_INTEGER * err);
void eos_MakeSmoothRecordType5 (void *ptr, EOS_INTEGER th, EOS_INTEGER dataType, EOS_BOOLEAN ptSmooth,
				EOS_INTEGER * err);
void eos_PrintRecordType5 (void *ptr, EOS_INTEGER th, EOS_CHAR * fname, EOS_INTEGER append, EOS_INTEGER * err);
void eos_SetFileIndexesRecordType5 (void *ptr, EOS_INTEGER th);
void eos_SetMonotonicityRecordType5 (void *me, EOS_INTEGER dataType, EOS_INTEGER inX, EOS_INTEGER inY);
void eos_SetPackedTableRecordType5 (void *ptr, EOS_INTEGER th, EOS_CHAR * packedTable, EOS_INTEGER * err);
void eos_SetSmoothingRecordType5 (void *me, EOS_INTEGER dataType, EOS_INTEGER makeSmooth,
				  EOS_INTEGER makePtSmooth);

#endif /* _EOS_RECORDTYPE5_INTERNAL_PROTOTYPES */

#endif /* EOS_RECORDTYPE5_PROTOTYPES */
