/*
 *..............................................................................................
 *  ./eos_version.c
 *    Version date: Sun Jan 17 10:22:07 MST 2021
 *    This file is automatically generated by eospac6.5.0alpha.1/Source/scripts/eos_version.pl
 *..............................................................................................
 */
#include "eos_types.h"
#include "eos_wrappers.h"
#include <string.h>

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef _EOS_INCLUDE_SPECIAL_FUNCTION
void eos_version_name_EOSPAC_v6_5_0alpha_1_62053188b9842842e41508c54196c533e0b91e51()
{
  return;
}
#endif

static EOS_CHAR *eos_version_info_msg = "EOSPAC v6.5.0alpha.1 62053188b9842842e41508c54196c533e0b91e51";
EOS_INTEGER _eos_get_version_length()
{
  /* include space for the '\0' character */
  return(strlen (eos_version_info_msg) + 1);
}
void FUNC_INTER eos_GetVersionLength(EOS_INTEGER *length)
{
  *length = _eos_get_version_length();
#ifdef USE_SPLUNK
  if (! _eos_splunk_get_acc_disable(EOS_SPLUNK_ACCUMULATOR_EOS_GETVERSIONLENGTH)) {
    EOS_CHAR val[800];
    sprintf(val, "length=%d", *length);
    _eos_splunk(EOS_SPLUNK_ACCUMULATOR_EOS_GETVERSIONLENGTH, val);
  }
#endif
}

EOS_CHAR* _eos_get_version()
{
  return(eos_version_info_msg);
}
void FUNC_INTER eos_GetVersion(EOS_CHAR *version)
{
  strcpy(version, _eos_get_version());
#ifdef USE_SPLUNK
  if (! _eos_splunk_get_acc_disable(EOS_SPLUNK_ACCUMULATOR_EOS_GETVERSION)) {
    _eos_splunk(EOS_SPLUNK_ACCUMULATOR_EOS_GETVERSION, version);
  }
#endif
  return;
}

#ifdef __cplusplus
}
#endif

