#! /bin/sh

loc=`dirname $0`
me=`basename $0`

_arch=`${loc}/config.guess.wrapper`

# process command line options
while getopts a:hn option;
do

  case "$option"
  in

      a) _arch=$OPTARG;;
      n) _arch=`${loc}/config.guess.wrapper -n`;;
      h) cat <<EOF >&2

Usage: ${me} [options] [DIR [, ...]]
   -a <ARCH> define an ARCH directory other than that of the current platform
   -h        display this help
   -n        pass through the -n option to config.guess.wrapper, so its result
             excludes the AVX string for the current platform
             (ie., x86_64-rhel7-linux-gnu instead of x86_64-avx512f-rhel7-linux-gnu)

EOF
        exit 2
        ;;

  esac

done

shiftcount=`expr $OPTIND - 1`
shift $shiftcount

pushd tests/${_arch}/$1/$2.workdir
printf "\n***         DEBUGGING: %s\n*** WORKING DIRECTORY: %s\n\n" $2 `pwd`

totalview ../$2 &
