#! /bin/sh
(shopt -s igncr) 2>/dev/null && eval 'shopt -s igncr';#

# $Date: 2016/11/29 21:57:10 $
#
# This script is used to define the location of modulecmd.
#

# define known possible locations for modulecmd
if   [ -x /usr/local/modules/$MODULE_VERSION/bin/modulecmd ] ; then
  MODULECMD=/usr/local/modules/$MODULE_VERSION/bin/modulecmd

elif [ -x /opt/modules/$MODULE_VERSION/bin/modulecmd ] ; then
  MODULECMD=/opt/modules/$MODULE_VERSION/bin/modulecmd

elif [ -x /opt/modules/default/bin/modulecmd ] ; then
  MODULECMD=/opt/modules/default/bin/modulecmd

elif [ -x /usr/share/modules/bin/modulecmd ] ; then
  MODULECMD=/usr/share/modules/bin/modulecmd

elif [ -x /usr/bin/modulecmd ] ; then
  MODULECMD=/usr/bin/modulecmd

elif [ -x /usr/share/lmod/lmod/libexec/lmod ] ; then
  MODULECMD=/usr/share/lmod/lmod/libexec/lmod

else
  MODULECMD=modulecmd_does_not_exist

fi
export MODULECMD

if [ "$1" == "verbose" ]; then
  printf "%s" "${MODULECMD}"
fi