#-*-makefile-*-###################################################
#  
#  Copyright -- see file named COPYRIGHTNOTICE
#  
##################################################################
### This file contains the following:                          ###
### Platform-dependent system configuration for an ARCH value  ###
### containing the following pattern:                          ###
###    *powerpc-ibm-aix
##################################################################
#
# GMSL 1.0.11 function dependencies exist (see $(BASEDIR)/config/gmsl).
#
# IBM PowerPC and AIX

##################################################################
# Compiler suite configurations based upon F90                 ###
##################################################################
# Default: use the first F90 compiler found from F90_List
F90_List = xlf90
F90 = $(firstword $(notdir $(foreach compiler,$(F90_List),$(call pathsearch,$(compiler)))))
ifeq ($(strip $(F90)),)
  $(error No supported Fortran compiler was found in your PATH for this machine. (supported: $(F90_List)))
endif

ifeq ($(strip $(F90)),xlf90)
  ALT_SUBDIR := $(shell $(BASEDIR)/scripts/define_module_subdir $(F90))
endif

##################################################################
### Assign values to associative arrays, which hold various    ###
### compiler options -- specific to this architecture.         ###
##################################################################
#
### VERSION_FLAG{$CC} = $flag
$(call set,VERSION_FLAG,xlc,-qversion)   # XL C
#
### VERSION_FLAG{$CXX} = $flag
$(call set,VERSION_FLAG,xlC,-qversion)   # XL C++
#
### VERSION_FLAG{$F77} = $flag
$(call set,VERSION_FLAG,f77,-qversion)   # XLF F77
#
### VERSION_FLAG{$F90} = $flag
$(call set,VERSION_FLAG,xlf90,-qversion)   # XLF F90
#
### _COMP_FLAGS{$CC} = $flag
#
### _COMP_FLAGS{$CXX} = $flag
#
### _COMP_FLAGS{$F77} = $flag
#
### _COMP_FLAGS{$F90} = $flag
$(call set,_COMP_FLAGS,xlf90,-qfloat=nomaf -qsuffix=f=f90)   # XLF F90

# Set additional compiler-specific options
_CFLAGS += $(call get,_COMP_FLAGS,$(CC))
_CXXFLAGS += $(call get,_COMP_FLAGS,$(CXX))
_FFLAGS += $(call get,_COMP_FLAGS,$(F77))
_F90FLAGS += $(call get,_COMP_FLAGS,$(F90))
