#-*-makefile-*-###################################################
#  
#  Copyright -- see file named COPYRIGHTNOTICE
#  
##################################################################
### This file contains the following:                          ###
### Platform-dependent system configuration for an ARCH value  ###
### containing the following pattern:                          ###
###    *sgi-irix
##################################################################
#
# GMSL 1.0.11 function dependencies exist (see $(BASEDIR)/config/gmsl).
#
# mips SGI and IRIX

##################################################################
# Compiler suite configurations based upon F90                 ###
##################################################################
# Default: use the first F90 compiler found from F90_List
F90_List = f90
F90 = $(firstword $(notdir $(foreach compiler,$(F90_List),$(call pathsearch,$(compiler)))))
ifeq ($(strip $(F90)),)
  $(error No supported Fortran compiler was found in your PATH for this machine. (supported: $(F90_List)))
endif

ifeq ($(strip $(F90)),f90)
  #(DAP)-- always use MIPSpro f77 compiler since g77 doesn't build correctly for SGI
  F77 = f77

  ifeq ($(strip $(N32)),)
    C_ADDRESS_FLAG := -mabi=64
    F_ADDRESS_FLAG := -64
    ALT_SUBDIR := 
  else
    C_ADDRESS_FLAG := 
    F_ADDRESS_FLAG := 
    ALT_SUBDIR := /n32
  endif
endif

##################################################################
### Assign values to associative arrays, which hold various    ###
### compiler options -- specific to this architecture.         ###
##################################################################
#
### VERSION_FLAG{$CC} = $flag
#
### VERSION_FLAG{$CXX} = $flag
#
### VERSION_FLAG{$F77} = $flag
$(call set,VERSION_FLAG,f77,-version)   # MIPSpro F77
#
### VERSION_FLAG{$F90} = $flag
$(call set,VERSION_FLAG,f90,-version)   # MIPSpro F90
#
### _COMP_FLAGS{$CC} = $flag
#
### _COMP_FLAGS{$CXX} = $flag
#
### _COMP_FLAGS{$F77} = $flag
#
### _COMP_FLAGS{$F90} = $flag

# Modify ARCH variable
ARCH   := $(shell $(BASEDIR)/scripts/config.guess)$(ALT_SUBDIR)

# Set additional compiler-specific options
_CFLAGS += $(call get,_COMP_FLAGS,$(CC))
_CXXFLAGS += $(call get,_COMP_FLAGS,$(CXX))
_FFLAGS += $(call get,_COMP_FLAGS,$(F77))
_F90FLAGS += $(call get,_COMP_FLAGS,$(F90))
