#-*-makefile-*-###################################################
#  
#  Copyright -- see file named COPYRIGHTNOTICE
#  
##################################################################
### This file contains the following:                          ###
### Platform-dependent system configuration for an ARCH value  ###
### containing the following pattern:                          ###
###    *pc-cygwin
##################################################################
#
# GMSL 1.0.11 function dependencies exist (see $(BASEDIR)/config/gmsl).
#
# Cygwin and MS Windows PC

##################################################################
# Compiler suite configurations based upon F90                 ###
##################################################################
#  use the first F90 compiler found from F90_List
F90_List = g95 gfortran
F90 = $(firstword $(notdir $(foreach compiler,$(F90_List),$(call pathsearch,$(compiler)))))
ifeq ($(strip $(F90)),)
  $(error No supported Fortran compiler was found in your PATH for this machine. (supported: $(F90_List)))
endif
MAKE_WINLIB_AR = $(WINLIB_AR)

ifeq ($(strip $(F90)),g95)
  G95_MEM_SEGMENTS = 0
  export G95_MEM_SEGMENTS
  ALT_SUBDIR := $(shell $(BASEDIR)/scripts/define_module_subdir $(F90) $(BASEDIR)/scripts)
endif

ifeq ($(strip $(F90)),gfortran)
  ALT_SUBDIR := $(shell $(BASEDIR)/scripts/define_module_subdir $(F90) $(BASEDIR)/scripts)
endif

##################################################################
### Assign values to associative arrays, which hold various    ###
### compiler options -- specific to this architecture.         ###
##################################################################
#
### VERSION_FLAG{$CC} = $flag
#
### VERSION_FLAG{$CXX} = $flag
#
### VERSION_FLAG{$F77} = $flag
#
### VERSION_FLAG{$F90} = $flag
#
### _COMP_FLAGS{$CC} = $flag
#
### _COMP_FLAGS{$CXX} = $flag
#
### _COMP_FLAGS{$F77} = $flag
#
### _COMP_FLAGS{$F90} = $flag

# Modify ARCH variable
ARCH   := $(shell $(BASEDIR)/scripts/config.guess)$(ALT_SUBDIR)

# Set additional compiler-specific options
_CFLAGS += $(call get,_COMP_FLAGS,$(CC))
_CXXFLAGS += $(call get,_COMP_FLAGS,$(CXX))
_FFLAGS += $(call get,_COMP_FLAGS,$(F77))
_F90FLAGS += $(call get,_COMP_FLAGS,$(F90))
