#-*-makefile-*-###################################################
#  
#  Copyright -- see file named COPYRIGHTNOTICE
#  
##################################################################
### This file contains the following:                          ###
### Platform-dependent system configuration for an ARCH value  ###
### containing the following pattern:                          ###
###    *sun-solaris
##################################################################
#
# GMSL 1.0.11 function dependencies exist (see $(BASEDIR)/config/gmsl).
#
# Sun and Solaris

##################################################################
# Compiler suite configurations based upon F90                 ###
##################################################################
# Default: use the first F90 compiler found from F90_List
F90_List = f90 gfortran
F90 = $(firstword $(notdir $(foreach compiler,$(F90_List),$(call pathsearch,$(compiler)))))
ifeq ($(strip $(F90)),)
  $(error No supported Fortran compiler was found in your PATH for this machine. (supported: $(F90_List)))
endif

ifeq ($(strip $(F90)),f90)
  F77 = f77
  ALT_SUBDIR := $(shell $(BASEDIR)/scripts/define_module_subdir $(F90))
endif

ifeq ($(strip $(F90)),gfortran)
  ALT_SUBDIR := $(shell $(BASEDIR)/scripts/define_module_subdir $(F90))
endif

##################################################################
### Assign values to associative arrays, which hold various    ###
### compiler options -- specific to this architecture.         ###
##################################################################
#
### VERSION_FLAG{$CC} = $flag
#
### VERSION_FLAG{$CXX} = $flag
#
### VERSION_FLAG{$F77} = $flag
$(call set,VERSION_FLAG,f77,-V)   # SUNWspro F77
#
### VERSION_FLAG{$F90} = $flag
#
### _COMP_FLAGS{$CC} = $flag
#
### _COMP_FLAGS{$CXX} = $flag
#
### _COMP_FLAGS{$F77} = $flag
#
### _COMP_FLAGS{$F90} = $flag
$(call set,_COMP_FLAGS,gfortran,-J$(INCDIR))   # GNU F90
$(call set,_COMP_FLAGS,f90,-M$(INCDIR))   # SUNWspro F90

# Set additional compiler-specific options
_CFLAGS += $(call get,_COMP_FLAGS,$(CC))
_CXXFLAGS += $(call get,_COMP_FLAGS,$(CXX))
_FFLAGS += $(call get,_COMP_FLAGS,$(F77))
_F90FLAGS += $(call get,_COMP_FLAGS,$(F90))
